version: '3'
services:
  backend:
    image: jgeven/mymanga:latest
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - spring_datasource_url=jdbc:mysql://mysql:3306/mymanga_management_system?useSSL=false
      - spring.datasource.hikari.initialization-fail-timeout=0
  mysql:
    container_name: mysqldatabase
    image: mysql:5.5.57
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mymanga_management_system
      - MYSQL_ROOT_PASSWORD=root